#!/bin/sh

set -e

python3.9 -m pip install p3lib
python3.9 -m pip install paho-mqtt
python3.9 -m pip install paramiko
python3.9 -m pip install texttable

echo "The icons_gw, icons_json_check and"
echo "mqtt_subscribe commands are now available."
