package vncv.view;
/*****************************************************************************************
 *                        Copyright 2013 Paul Austen                                     *
 *                                                                                       *
 * This program is distributed under the terms of the GNU Lesser General Public License  *
 *****************************************************************************************/

/**
 * Exception generated by the VNCV application.
 */
public class VNCVException extends Exception
{

  public VNCVException(String message)
  {
    super(message);
  }
}